language: bash

services: docker

env:
  global:
    - secure: "yRUMaooh1bc7SHpg4g4AWbRp1q1RWg5xfcQ+lUUjE6oZacA3t9t3aY+M18MhJFTkJ987+iF9LrrgKEZOB/PgR6ziTy9YeXIiA7j/p+d7WCKMl9ym75uNc89wB99WZGxHhrRFhfaBGCbDL9jKbYKAa8OsQ1HM2W7cUFK75hhPE/69ZzfGq4j8c4HfKqMusjyLy/2o95X7i8sHMQ5Z2FL0WPvqWOdkPSsdQ1a8Uu8RJmWukqDwWlb2bVhbAoT/RcGRKfe0a6hIUNlrgjaIPvGT+XJAhbq/b79+2eZKsJIk72OwSWRVI2lByJXhJ7g/hdXbq4qXmKSmgMoKO4xzqxLTFV7VJZIsMCqfyDst6CsAHhV1xHoxYj5+8g0nYkgsXBVkU2+UyRAR2mK+FpWOZl6JhMcsQLSr999HxQIO1spYqDrdt9BPIGPm7549y7HBDFyy2WmAXayiGYzG23U4pfvpaIYwIZvokPI/oyA4MSMMeAP2Eu8d8qKnzh+vRPY5TDm+3fcCKAW+Y090em4HZ9xRXYKp4WF8Q/9RdDJONSGRzGvghDtqQ+i2vJfBkMljHuj9g9T5JM+m7AC7v/NJSJCUbxt3vte4sNm89KkSfQP/YQzVv2id3trntPBXfF8FManXZ3Opc2tWllByxzokJW9aU5JlTI25ZIPf1AD14KTqsBI="
    - secure: "oDmN64oChE+0iWWFtcTSncznlKfvs3zjtDMcrkKKNdYbrOvB1gHRZgjOHJrE3fAIogAQ6P1DJ5ytGYsPODd4wo8YlRX65QBHVExSxw0Yxqj8YMKo5Cl0JAb/BiGwgFURbonzCqcT1w1GUhk4d/BWt5INvos+fUmY59EToUDdXcC5sn/bA4/ykFE/56wOn9kMayF7GQkmXuJFQ8PK+eg6NyZtwfn5TywWCccmD3AXVSqRK+yyhyw/qffOSGmJbfn9fHnR7Wj0XD8Bg4BdXosCHRc3CkyJUw1AUNPGg92zVt20IDXz33w//sE+0v55cnkkpyf8kS1qg0Tpi6EbWt48XfzjScNc5i9JqvB64ofnQh3yw6GUXIjcRE0JR1SHXOFzTFoE7IRTUy+Y+kpHL7HxDi14MAQBWHG+loszouJZQAoxAEJ7TxudoUqtVjJPYmDbVcTG2MijSBqYIbtONVoCywkPM+ypVR9GWWK6xouccBq3NMM9vxe7umXDP4x+Nk2rReG5kRnw8cToRq3SUIfd5wNBAjjvxLdXVp+BuGqvmpWSYaxJA79BqROqmEa8vHH6tzZ+Qybjzpef62IAOeKj5/9YHKJn1kKikPEb/TTCABNjEZyaXXjHbxorkUcmfwMIE/hAjwBfmecoN8tp7CV3zwd5t4B1VJ6hb+AphTHCxoE="
  matrix:
    - VERSION=latest

before_script:
  - cd src/
  - IMAGE_NAME="chesszebra/$(echo "$TRAVIS_REPO_SLUG" | cut -c 25-):${VERSION}"

script:
  - docker build -t "$IMAGE_NAME" .

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push $IMAGE_NAME

after_script:
  - docker images

notifications:
  email: false
